[envs.base]
channels = ["conda-forge"]
platform = "linux-64"
[envs.base.dependencies]
aria2 = "*"          # CLI download manager
cmake = "*"          # Build system
curl = "*"           # Command line tool for transferring data with URLs
gh = "*"             # GitHub CLI
git = "*"            # version control
go-yq = "*"          # YAML processor
imagemagick = "*"    # Image processing
jq = "*"             # JSON processor
p7zip = "*"          # 7-Zip file archiver
pkg-config = "*"     # Helper tool for compiling applications and libraries
powershell = "*"     # Cross-platform automation and configuration tool
wget = "*"           # Network downloader
zstd = "*"           # Zstandard compression

[envs.base.exposed]
7z = "7z"
aria2 = "aria2c"
cmake = "cmake"
curl = "curl"
gh = "gh"
git = "git"
jq = "jq"
magick = "magick"
pkg-config = "pkg-config"
pwsh = "pwsh"
wget = "wget"
yq = "yq"
zstd = "zstd"
