[envs.base]
channels = ["https://prefix.dev/glatzel", "conda-forge"]

[envs.base.dependencies]
7-zip = "*"
aria2 = "*"
ca-certificates = "*"
curl = "*"
gh = "*"
git = "*"
gzip = "*"
jq = "*"
tar = "*"
unzip = "*"
wget = "*"
zip = "*"
zstd = "*"

[envs.base.exposed]
7z = "7z"
aria2 = "aria2c"
curl = "curl"
gh = "gh"
git = "git"
gzip = "gzip"
jq = "jq"
tar = "tar"
unzip = "unzip"
wget = "wget"
zip = "zip"
zstd = "zstd"

[envs.powershell]
channels = ["conda-forge"]
[envs.powershell.dependencies]
powershell = "*"
[envs.powershell.exposed]
pwsh = "pwsh"
