[envs.base]
channels = ["conda-forge"]
[envs.base.dependencies]
aria2 = "*"       # CLI download manager
cmake = "3.*"     # Build system
curl = "*"        # Command line tool for transferring data with URLs
gh = "*"          # GitHub CLI
git = "*"         # version control
go-yq = "*"       # YAML processor
gzip = "*"
imagemagick = "*" # Image processing
jq = "*"          # JSON processor
libtool = "*"
p7zip = "*"       # 7-Zip file archiver
powershell = "*"  # Cross-platform automation and configuration tool
tar = "*"
unzip = "*"
wget = "*"        # Network downloader
zip = "*"
zstd = "*"        # Zstandard compression

[envs.base.exposed]
7z = "7z"
aria2 = "aria2c"
cmake = "cmake"
curl = "curl"
gh = "gh"
git = "git"
gzip = "gzip"
jq = "jq"
libtool = "libtool"
magick = "magick"
pwsh = "pwsh"
tar = "tar"
unzip = "unzip"
wget = "wget"
yq = "yq"
zip = "zip"
zstd = "zstd"
