[envs.base]
channels = ["conda-forge"]
[envs.base.dependencies]
aria2 = "*"       # CLI download manager
cmake = "3.*"     # Build system
curl = "*"        # Command line tool for transferring data with URLs
gcc = "*"
gh = "*"          # GitHub CLI
git = "*"         # version control
go-yq = "*"       # YAML processor
imagemagick = "*" # Image processing
jq = "*"          # JSON processor
make = "*"
p7zip = "*"       # 7-Zip file archiver
pkg-config = "*"  # Helper tool for compiling applications and libraries
powershell = "*"  # Cross-platform automation and configuration tool
tar = "*"
unzip = "*"
wget = "*"        # Network downloader
zip = "*"
zstd = "*"        # Zstandard compression

[envs.base.exposed]
7z = "7z"
aria2 = "aria2c"
cmake = "cmake"
curl = "curl"
gcc = "gcc"
gh = "gh"
git = "git"
jq = "jq"
magick = "magick"
make = "make"
pkg-config = "pkg-config"
pwsh = "pwsh"
tar = "tar"
unzip = "unzip"
wget = "wget"
yq = "yq"
zip = "zip"
zstd = "zstd"
