[envs.base]
channels = ["conda-forge"]

[envs.base.dependencies]
7zip = "*"
aria2 = "*"
ca-certificates = "*"
curl = "*"
gh = "*"
git = "*"
gzip = "*"
jq = "*"
powershell = "*"
tar = "*"
unzip = "*"
wget = "*"
zip = "*"
zstd = "*"

[envs.base.exposed]
7z = "7zz"
aria2 = "aria2c"
curl = "curl"
gh = "gh"
git = "git"
gzip = "gzip"
jq = "jq"
pwsh = "pwsh"
tar = "tar"
unzip = "unzip"
wget = "wget"
zip = "zip"
zstd = "zstd"
