[envs.base]
channels = ["https://prefix.dev/glatzel", "conda-forge"]

[envs.base.dependencies]
7-zip = "*"
aria2 = "*"
ca-certificates = "*"
curl = "*"
gh = "*"
git = "*"
jq = "*"

[envs.base.exposed]
7z = "7z"
aria2 = "aria2c"
curl = "curl"
gh = "gh"
git = "git"
jq = "jq"

[envs.runner]
channels = ["https://prefix.dev/glatzel"]
[envs.runner.dependencies]
github-action-runner = "*"

[envs.powershell]
channels = ["conda-forge"]
[envs.powershell.dependencies]
powershell = "*"
[envs.powershell.exposed]
pwsh = "pwsh"
