[envs.base-ci]
channels = ["conda-forge"]
platform = "linux-64"
[envs.base-conda.dependencies]
aria2 = "*"          # CLI download manager
cargo-llvm-cov = "*" # LLVM coverage for Cargo
cargo-nextest = "*"  # Next-generation test runner for Rust
cmake = "*"          # Build system
curl = "*"           # Command line tool for transferring data with URLs
gh = "*"             # GitHub CLI
git = "*"            # version control
git-cliff = "*"      # Git commit message linter
go-yq = "*"          # YAML processor
imagemagick = "*"    # Image processing
jq = "*"             # JSON processor
p7zip = "*"          # 7-Zip file archiver
pkg-config = "*"     # Helper tool for compiling applications and libraries
powershell = "*"     # Cross-platform automation and configuration tool
ruff = "*"           # Fast Python linter
wget = "*"           # Network downloader
zstd = "*"           # Zstandard compression
[envs.base-ci.exposed]
7z = "7z"
aria2 = "aria2c"
cargo-llvm-cov = "cargo-llvm-cov"
cargo-nextest = "cargo-nextest"
cmake = "cmake"
curl = "*"
gh = "gh"
git = "git"
git-cliff = "git-cliff"
jq = "jq"
magick = "magick"
pkg-config = "pkg-config"
pwsh = "pwsh"
ruff = "ruff"
wget = "wget"
yq = "yq"
zstd = "zstd"
