version = 1

[envs.dev-tool]
channels = ["conda-forge"]

[envs.dev-tool.dependencies]
aria2 = "*"
cargo-llvm-cov = "*"
cargo-nextest = "*"
cmake = "*"
gh = "*"
git-cliff = "*"
jq = "*"
nomkl = "*"
p7zip = "*"
pkg-config = "*"
powershell = "*"
python = "3.13.*"
ruff = "*"
zstd = "*"

[envs.dev-tool.exposed]
7z = "7z"
aria2 = "aria2c"
cargo-llvm-cov = "cargo-llvm-cov"
cargo-nextest = "cargo-nextest"
cmake = "cmake"
gh = "gh"
git-cliff = "git-cliff"
jq = "jq"
pkg-config = "pkg-config"
pwsh = "pwsh"
ruff = "ruff"
zstd = "zstd"
