[envs.base]
channels = ["conda-forge"]
[envs.base.dependencies]
aria2 = "*"
cmake = "3.*"
curl = "*"
gh = "*"
git = "*"
go-yq = "*"
gzip = "*"
imagemagick = "*"
jq = "*"
libtool = "*"
p7zip = "*"
powershell = "*"
tar = "*"
unzip = "*"
wget = "*"
zip = "*"
zstd = "*"

[envs.base.exposed]
7z = "7z"
aria2 = "aria2c"
cmake = "cmake"
curl = "curl"
gh = "gh"
git = "git"
gzip = "gzip"
jq = "jq"
libtool = "libtool"
magick = "magick"
pwsh = "pwsh"
tar = "tar"
unzip = "unzip"
wget = "wget"
yq = "yq"
zip = "zip"
zstd = "zstd"
